import type { IssueSeed } from "./cxalloy";

/** Active Holder Mustang PRL1A CXAlloy list (printed 08.10.2026). */
export const MUSTANG_ISSUES: IssueSeed[] = [
  {
    "code": "CHK-266-2",
    "title": "Switchgear ATC Panel Section: 1 of 6, Multiple ferrule terminations inserted too far in to CB screw lugs.",
    "description": "Switchgear ATC Panel Section: 1 of 6, Multiple ferrule terminations inserted too far in to CB screw lugs. Two ferrule connectors damaged. SN: D25276011-SN004",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/03/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:04 PM"
  },
  {
    "code": "CHK-266-4",
    "title": "Section: 3 of 6, Long barrel lug from GEN Panel breaker to B-Phase bus needs an addition crimp applied.",
    "description": "Section: 3 of 6, Long barrel lug from GEN Panel breaker to B-Phase bus needs an addition crimp applied. Only three crimps present on lug, lug calls for four total crimps in each designated area. SN: D25276011-SN004",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/03/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:17 PM"
  },
  {
    "code": "CHK-266-5",
    "title": "GEN Panel Breaker 150AF/100AT Section: 3 of 6, Missing labels",
    "description": "GEN Panel Breaker 150AF/100AT Section: 3 of 6, Missing labels",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:24 PM"
  },
  {
    "code": "CHK-266-6",
    "title": "GEN Panel Breaker 150AF/100AT Section: 3 of 6, Loose ground braid hardware on panel door.",
    "description": "GEN Panel Breaker 150AF/100AT Section: 3 of 6, Loose ground braid hardware on panel door.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:26 PM"
  },
  {
    "code": "CHK-266-7",
    "title": "SPD Breaker 60AT Section: 5 of 6, Missing labels",
    "description": "SPD Breaker 60AT Section: 5 of 6, Missing labels",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c1",
    "discipline": "",
    "type": "",
    "dueDate": "06/26/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:26 PM"
  },
  {
    "code": "CHK-268-1",
    "title": "Switchgear ATC Panel Section: 1 of 6, All three door latches have loose hardware and needs to be properly tightened.",
    "description": "Switchgear ATC Panel Section: 1 of 6, All three door latches have loose hardware and needs to be properly tightened. SN: D25276011-SN003",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-a3",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:40 PM"
  },
  {
    "code": "CHK-268-3",
    "title": "SPD Breaker 150AF/100AT Section: 5 of 6, Missing labels",
    "description": "SPD Breaker 150AF/100AT Section: 5 of 6, Missing labels",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-a3",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:45 PM"
  },
  {
    "code": "CHK-268-7",
    "title": "Control wires for section one have multiple tags on them.",
    "description": "Control wires for section one have multiple tags on them. We don’t know where they land.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-a3",
    "discipline": "",
    "type": "",
    "dueDate": "08/03/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/28/2026 7:29 AM"
  },
  {
    "code": "CHK-269-1",
    "title": "Switchgear ATC Panel Section: 1 of 6, Missing labels",
    "description": "Switchgear ATC Panel Section: 1 of 6, Missing labels",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:31 PM"
  },
  {
    "code": "CHK-269-2",
    "title": "Switchgear ATC panel Section: 1 of 6, Middle door latch hardware loose and needs to be properly tightened.",
    "description": "Switchgear ATC panel Section: 1 of 6, Middle door latch hardware loose and needs to be properly tightened.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:33 PM"
  },
  {
    "code": "CHK-269-4",
    "title": "GEN 150AF/100AT Section: 3 of 6, Missing labels",
    "description": "GEN 150AF/100AT Section: 3 of 6, Missing labels",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "06/19/2026 12:37 PM"
  },
  {
    "code": "CHK-274-1",
    "title": "Feeder breaker #2 spring return lever (Cradle Latch) moves freely and does not allow spring return.",
    "description": "Feeder breaker #2 The spring return lever (Cradle Latch) on the side of the breaker moves freely, does not allow spring return.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-a1",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Roger Schultz",
    "identifiedOn": "07/16/2026 9:33 AM"
  },
  {
    "code": "CHK-278-1",
    "title": "Section 1 - ATC PANEL - Bottom Door Latch is misaligned and not seating to enclosure",
    "description": "Section 1 - ATC PANEL - Bottom Door Latch is misaligned and not seating to enclosure",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c3",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/16/2026 10:06 AM"
  },
  {
    "code": "CHK-278-2",
    "title": "Section 3 - Back / Middle Cover Plate - Bowed Inward",
    "description": "Section 3 - Back / Middle Cover Plate - Bowed Inward",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c3",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/16/2026 10:06 AM"
  },
  {
    "code": "CHK-278-3",
    "title": "Section 6 - Bottom / Right - Cover Plate Has Dent On Top Of Cover.",
    "description": "Section 6 - Bottom / Right - Cover Plate Has Dent On Top Of Cover.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c3",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/16/2026 10:06 AM"
  },
  {
    "code": "CHK-279-1",
    "title": "Section 6 - Back / Middle Cover Plate - Bowed Inward",
    "description": "Section 6 - Back / Middle Cover Plate - Bowed Inward",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-1-d1",
    "discipline": "",
    "type": "",
    "dueDate": "08/06/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/30/2026 8:39 AM"
  },
  {
    "code": "CHK-280-1",
    "title": "Section 1 - ATC CABINET - Back / Middle Cover Panel - Bowed Inward",
    "description": "Section 1 - ATC CABINET - Back / Middle Cover Panel - Bowed Inward",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d3",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/16/2026 2:12 PM"
  },
  {
    "code": "CHK-283-1",
    "title": "Red board spring loaded shutters behind feeder breakers are not operating correctly and staying exposed after breakers has been removed",
    "description": "Red board spring loaded shutters behind feeder breakers are not operating correctly and staying exposed after breakers has been removed",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-b2",
    "discipline": "",
    "type": "",
    "dueDate": "07/20/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/13/2026 2:34 PM"
  },
  {
    "code": "CHK-283-2",
    "title": "Gen Breaker 4000 Amp — BLUE Reset push button is broken",
    "description": "Gen Breaker 4000 Amp. BLUE Reset push button on front of breaker is broken.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-b2",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "",
    "createdBy": "Paul Ide",
    "identifiedOn": ""
  },
  {
    "code": "CHK-283-3",
    "title": "Section 6, inside bar, neutral main, Belleville washer is backward from factory",
    "description": "Section 6, inside bar, neutral main, Belleville washer is backward from factory",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-b2",
    "discipline": "",
    "type": "",
    "dueDate": "07/30/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/23/2026 1:46 PM"
  },
  {
    "code": "CHK-284-2",
    "title": "Section 4 - Bus Plug Insulator Not Functioning Properly",
    "description": "Section 4 - Bus Plug Insulator Not Functioning Properly",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P1",
    "priorityLabel": "HIGH",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-c2",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/16/2026 3:27 PM"
  },
  {
    "code": "CHK-284-3",
    "title": "Section 5 - Top / Back Cover Panel - Dented Inward",
    "description": "Section 5 - Top / Back Cover Panel - Dented Inward",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-c2",
    "discipline": "",
    "type": "",
    "dueDate": "07/23/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/17/2026 5:50 AM"
  },
  {
    "code": "CHK-284-6",
    "title": "Tags are reversed",
    "description": "Tags are reversed",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-c2",
    "discipline": "",
    "type": "",
    "dueDate": "08/14/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "08/10/2026 7:33 AM"
  },
  {
    "code": "CHK-285-1",
    "title": "Heat shrink is missing from spare breaker load side lug.",
    "description": "Heat shrink is missing from spare breaker load side lug.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-d2",
    "discipline": "",
    "type": "",
    "dueDate": "08/13/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "08/06/2026 11:22 AM"
  },
  {
    "code": "CHK-287-6",
    "title": "Bent cover panel on back of section one",
    "description": "Bent cover panel on back of section one",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-n",
    "discipline": "",
    "type": "",
    "dueDate": "07/17/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/10/2026 1:30 PM"
  },
  {
    "code": "CHK-288-4",
    "title": "LVCB MOTOR CRAH-10 (CHK-288-4) High Contact Resistance reading C Phase The reading recorded is more than 50% of the lowest Value",
    "description": "LVCB MOTOR CRAH-10 (CHK-288-4) High Contact Resistance reading C Phase The reading recorded is more than 50% of the lowest Value",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-o",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "06/24/2026",
    "createdBy": "Roger Schultz",
    "identifiedOn": "06/17/2026 1:47 PM"
  },
  {
    "code": "CHK-288-5",
    "title": "New phenolic label is needed, this one is cracked",
    "description": "New phenolic label is needed, this one is cracked",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-o",
    "discipline": "",
    "type": "",
    "dueDate": "07/21/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/14/2026 10:25 AM"
  },
  {
    "code": "CHK-289-1",
    "title": "Section 4 has a bent back cover",
    "description": "Section 4 has a bent back cover",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-a2",
    "discipline": "",
    "type": "",
    "dueDate": "08/05/2026",
    "createdBy": "Paul Ide",
    "identifiedOn": "07/29/2026 11:43 AM"
  },
  {
    "code": "CHK-291-1",
    "title": "Section 4 - Back/Middle Cover Plate Bowed Inward.",
    "description": "Section 4 - Back/Middle Cover Plate Bowed Inward.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-c2",
    "discipline": "",
    "type": "",
    "dueDate": "07/16/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/09/2026 2:44 PM"
  },
  {
    "code": "CHK-292-1",
    "title": "Section 6 - Back/Middle Cover Plate Bowed Inward",
    "description": "Section 6 - Back/Middle Cover Plate Bowed Inward",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-d2",
    "discipline": "",
    "type": "",
    "dueDate": "07/17/2026",
    "createdBy": "Scott Thrasher",
    "identifiedOn": "07/10/2026 10:21 AM"
  },
  {
    "code": "CHK-292-3",
    "title": "Section: 3 of 6, SPD breaker feeder wires (Neutral) has improper crimp applied to long barrel lug.",
    "description": "Section: 3 of 6, SPD breaker feeder wires (Neutral) has improper crimp applied to long barrel lug. S/N: D25276011-SN007",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-d2",
    "discipline": "",
    "type": "",
    "dueDate": "08/04/2026",
    "createdBy": "Adam LaGrand",
    "identifiedOn": "07/20/2026 9:55 AM"
  },
  {
    "code": "CHK-1035-3",
    "title": "Loose wires in the main breaker cabinet",
    "description": "Loose wires in the main breaker cabinet",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-j",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/13/2026",
    "createdBy": "Jonathon Oaks",
    "identifiedOn": "07/06/2026 3:29 PM"
  },
  {
    "code": "CHK-1035-4",
    "title": "Breaker Cabinet 6 and 7 in PMDC has loose control wiring",
    "description": "Breaker Cabinet 6 and 7 in PMDC has loose control wiring",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-j",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/16/2026",
    "createdBy": "Jonathon Oaks",
    "identifiedOn": "07/09/2026 12:57 PM"
  },
  {
    "code": "CHK-1828-1",
    "title": "MISSING BOLT",
    "description": "MISSING BOLT",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-1-o",
    "discipline": "",
    "type": "",
    "dueDate": "09/11/2026",
    "createdBy": "Michael McKinney",
    "identifiedOn": "08/05/2026 1:56 PM"
  },
  {
    "code": "CHK-1834-1",
    "title": "front cover plate on section 5 & 6 present dent on the left side (not flush with right cover) see picture for details",
    "description": "front cover plate on section 5 & 6 present dent on the left side (not flush with right cover) see picture for details",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-c3",
    "discipline": "Electrical",
    "type": "QA/QC",
    "dueDate": "08/12/2026",
    "createdBy": "Luis Colon",
    "identifiedOn": "08/06/2026 8:13 AM"
  },
  {
    "code": "CHK-1836-1",
    "title": "back side of the PMDC on section 4 & 5 are missing screws (two in section 4 and one in section 5) both in upper cover.",
    "description": "back side of the PMDC on section 4 & 5 are missing screws (two in section 4 and one in section 5) both in upper cover.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d3",
    "discipline": "Electrical",
    "type": "QA/QC",
    "dueDate": "08/13/2026",
    "createdBy": "Luis Colon",
    "identifiedOn": "08/07/2026 7:53 AM"
  },
  {
    "code": "CHK-1836-2",
    "title": "Front left cover on section 5 and 6 Bowed Inward (see pictures for details)",
    "description": "Front left cover on section 5 and 6 Bowed Inward (see pictures for details)",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC A-2-d3",
    "discipline": "Electrical",
    "type": "QA/QC",
    "dueDate": "08/13/2026",
    "createdBy": "Luis Colon",
    "identifiedOn": "08/07/2026 8:00 AM"
  },
  {
    "code": "CHK-1841-1",
    "title": "PMDC B-1-m Section 3 of 5 is missing a breaker filler plate.",
    "description": "PMDC B-1-m Section 3 of 5 is missing a breaker filler plate. Phenolic tag states \"B-1-n\".",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-m",
    "discipline": "Electrical",
    "type": "QA/QC",
    "dueDate": "08/12/2026",
    "createdBy": "Donovan Harmon",
    "identifiedOn": "08/06/2026 1:55 PM"
  },
  {
    "code": "CHK-1843-1",
    "title": "PMDC B-1-o section 1 incorrect phenolic tag.",
    "description": "PMDC B-1-o section 1 incorrect phenolic tag.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P3",
    "priorityLabel": "LOW",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-1-o",
    "discipline": "Electrical",
    "type": "QA/QC",
    "dueDate": "08/12/2026",
    "createdBy": "Donovan Harmon",
    "identifiedOn": "08/06/2026 2:26 PM"
  },
  {
    "code": "FO-24-1",
    "title": "During FOAK the UL Label is damaged on PMDC section 6",
    "description": "During FOAK the UL Label is damaged on PMDC section 6",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P1",
    "priorityLabel": "HIGH",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-a2",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/01/2026",
    "createdBy": "Brian Harper",
    "identifiedOn": "06/25/2026 4:48 PM"
  },
  {
    "code": "FO-24-16",
    "title": "Label on entire board need to be Orange to reflect 416v AC",
    "description": "Label on entire board need to be Orange to reflect 416v AC",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P2",
    "priorityLabel": "MODERATE",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-a2",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/01/2026",
    "createdBy": "Brian Harper",
    "identifiedOn": "06/26/2026 3:46 PM"
  },
  {
    "code": "FO-24-23",
    "title": "ERMS Settings on breakers per specification are to be set to minimum.",
    "description": "ERMS Settings on breakers per specification are to be set to minimum. As found typically on all ERMS breakers, this is not the case.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P1",
    "priorityLabel": "HIGH",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-a2",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/02/2026",
    "createdBy": "Brian Harper",
    "identifiedOn": "06/30/2026 9:46 AM"
  },
  {
    "code": "FO-24-24",
    "title": "Ground lug bolt missing washer on ground bar in Utility section of PMDC underneath bolt head and at other locations.",
    "description": "Ground lug bolt missing washer on ground bar in Utility section of PMDC underneath bolt head and at other locations.",
    "status": "in_progress",
    "statusLabel": "IN PROGRESS",
    "priority": "P1",
    "priorityLabel": "HIGH",
    "assignedTo": "Mission Critical Group",
    "asset": "PMDC B-2-a2",
    "discipline": "Electrical",
    "type": "",
    "dueDate": "07/02/2026",
    "createdBy": "Brian Harper",
    "identifiedOn": "06/30/2026 9:46 AM"
  }
];
