/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ProjectProjectIdEditRouteImport } from './routes/project.$projectId.edit'
import { Route as ProjectProjectIdExportRouteImport } from './routes/project.$projectId.export'
import { Route as ProjectProjectIdIssuesRouteImport } from './routes/project.$projectId.issues'
import { Route as ProjectProjectIdReportReportIdRouteImport } from './routes/project.$projectId.report.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdEditRoute = ProjectProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdExportRoute = ProjectProjectIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdIssuesRoute = ProjectProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdReportReportIdRoute =
  ProjectProjectIdReportReportIdRouteImport.update({
    id: '/report/$reportId',
    path: '/report/$reportId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/export': typeof ProjectProjectIdExportRoute
  '/project/$projectId/issues': typeof ProjectProjectIdIssuesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/report/$reportId': typeof ProjectProjectIdReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/export': typeof ProjectProjectIdExportRoute
  '/project/$projectId/issues': typeof ProjectProjectIdIssuesRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/report/$reportId': typeof ProjectProjectIdReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/export': typeof ProjectProjectIdExportRoute
  '/project/$projectId/issues': typeof ProjectProjectIdIssuesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/report/$reportId': typeof ProjectProjectIdReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/new'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/project/$projectId/edit'
    | '/project/$projectId/export'
    | '/project/$projectId/issues'
    | '/project/$projectId/'
    | '/project/$projectId/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/new'
    | '/api/auth/$'
    | '/project/$projectId/edit'
    | '/project/$projectId/export'
    | '/project/$projectId/issues'
    | '/project/$projectId'
    | '/project/$projectId/report/$reportId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/new'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/project/$projectId/edit'
    | '/project/$projectId/export'
    | '/project/$projectId/issues'
    | '/project/$projectId/'
    | '/project/$projectId/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NewRoute: typeof NewRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/edit': {
      id: '/project/$projectId/edit'
      path: '/edit'
      fullPath: '/project/$projectId/edit'
      preLoaderRoute: typeof ProjectProjectIdEditRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/export': {
      id: '/project/$projectId/export'
      path: '/export'
      fullPath: '/project/$projectId/export'
      preLoaderRoute: typeof ProjectProjectIdExportRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/issues': {
      id: '/project/$projectId/issues'
      path: '/issues'
      fullPath: '/project/$projectId/issues'
      preLoaderRoute: typeof ProjectProjectIdIssuesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/report/$reportId': {
      id: '/project/$projectId/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/project/$projectId/report/$reportId'
      preLoaderRoute: typeof ProjectProjectIdReportReportIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdEditRoute: typeof ProjectProjectIdEditRoute
  ProjectProjectIdExportRoute: typeof ProjectProjectIdExportRoute
  ProjectProjectIdIssuesRoute: typeof ProjectProjectIdIssuesRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdReportReportIdRoute: typeof ProjectProjectIdReportReportIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdEditRoute: ProjectProjectIdEditRoute,
  ProjectProjectIdExportRoute: ProjectProjectIdExportRoute,
  ProjectProjectIdIssuesRoute: ProjectProjectIdIssuesRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdReportReportIdRoute: ProjectProjectIdReportReportIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NewRoute: NewRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
